In [60]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/faizanhaider01/heart-attack-chances/heart_data.csv

In [61]:
df = pd.read_csv('/kaggle/input/datasets/faizanhaider01/heart-attack-chances/heart_data.csv')

In [62]:
df.sample(5)

             Name   Age  Blood_Pressure  Cholesterol  Heart_Attack_Chance_%
7      Amna Zahid  58.0             149          258                  84.89
24    Kamran Baig  49.0             175          275                  78.15
21     Amna Zahid  21.0             121          188                  93.80
194  Shahid Latif  34.0             158          217                  83.62
128      Ali Khan  63.0             154          150                  51.83

In [63]:
df.isnull().mean()*100

Name                      0.0
Age                      22.0
Blood_Pressure            0.0
Cholesterol               0.0
Heart_Attack_Chance_%     0.0
dtype: float64

In [73]:
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [66]:
X = df.drop(columns=['Heart_Attack_Chance_%', 'Heart_Attack_Risk', 'Name'])
y = df['Heart_Attack_Risk']

In [67]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [68]:
X_train

      Age  Blood_Pressure  Cholesterol
137   NaN             135          254
163  54.0             171          294
111  43.0             105          250
123  44.0             150          266
109   NaN             158          214
..    ...             ...          ...
43   66.0             149          250
22   43.0             176          166
72    NaN              90          283
15   55.0             105          167
168  20.0             101          283

[160 rows x 3 columns]

In [74]:
knn = KNNImputer(n_neighbors=3,weights = 'distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [76]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.45

In [77]:

# Comparision with Simple Imputer --> mean

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [78]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred2)

0.45