In [66]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/spscientist/students-performance-in-exams/StudentsPerformance.csv
/kaggle/input/datasets/faizanhaider01/custom/customer.csv

In [67]:
df = pd.read_csv('/kaggle/input/datasets/faizanhaider01/custom/customer.csv')
df.sample(6)

    age  gender   review education purchased
26   53  Female     Poor        PG        No
43   27    Male     Poor        PG        No
48   39  Female     Good        UG       Yes
46   64  Female     Poor        PG        No
21   32    Male  Average        PG        No
12   51    Male     Poor    School        No

In [68]:
from sklearn.preprocessing import OrdinalEncoder
df = df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [69]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [70]:
Y_test

10    Yes
11    Yes
42    Yes
2      No
21     No
4      No
45    Yes
32    Yes
14    Yes
7     Yes
Name: purchased, dtype: object

In [71]:
X_train

     review education
29  Average        UG
34  Average    School
41     Good        PG
17     Poor        UG
3      Good        PG
16     Poor        UG
18     Good    School
30  Average        UG
9      Good        UG
24  Average        PG
35     Poor    School
48     Good        UG
33     Good        PG
27     Poor        PG
44  Average        UG
22     Poor        PG
37  Average        PG
40     Good    School
26     Poor        PG
13  Average    School
46     Poor        PG
49     Good        UG
5   Average    School
19     Poor        PG
23     Good    School
8   Average        UG
25     Good    School
47     Good        PG
20  Average    School
39     Poor        PG
1      Poor        UG
31     Poor    School
28     Poor    School
15     Poor        UG
43     Poor        PG
12     Poor    School
6      Good    School
0   Average    School
36     Good        UG
38     Good    School

In [72]:
ord_encoder = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','PG','UG']])

In [73]:
ord_encoder.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'PG', 'UG']])

In [74]:
X_train = ord_encoder.transform(X_train)

In [75]:
X_train

array([[1., 2.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [2., 0.]])

In [76]:
X_test = ord_encoder.transform(X_test)

In [77]:
X_test

array([[2., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [1., 2.],
       [0., 1.],
       [1., 2.],
       [0., 1.],
       [0., 0.]])

In [78]:
from sklearn.preprocessing import LabelEncoder

In [79]:
lb = LabelEncoder()

In [80]:
lb.fit(Y_train)
lb.classes_

array(['No', 'Yes'], dtype=object)

In [81]:
Y_train=lb.transform(Y_train)
Y_test = lb.transform(Y_test)

In [82]:
Y_test

array([1, 1, 1, 0, 0, 0, 1, 1, 1, 1])