In [97]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/faizanhaider01/titanic/Titanic Dataset.csv

In [98]:
df = pd.read_csv("/kaggle/input/datasets/faizanhaider01/titanic/Titanic Dataset.csv")

In [99]:
df.sample(5)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
593,2,1,"West, Mrs. Edwy Arthur (Ada Mary Worth)",female,33.0,1,2,C.A. 34651,27.750,NaN,S,10,NaN,"Bournmouth, England"
951,3,0,"Larsson, Mr. Bengt Edvin",male,29.0,0,0,347067,7.775,NaN,S,NaN,NaN,NaN
515,2,1,"Navratil, Master. Michel M",male,3.0,1,1,230080,26.000,F2,S,D,NaN,"Nice, France"
1220,3,0,"Spinner, Mr. Henry John",male,32.0,0,0,STON/OQ. 369943,8.050,NaN,S,NaN,NaN,NaN
300,1,0,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.500,B19,S,NaN,245.0,"Brooklyn, NY"

In [100]:
df.drop(columns= ['name','ticket','cabin','boat','body','home.dest'],inplace=True)

In [101]:
df.sample(5)

     pclass  survived     sex   age  sibsp  parch     fare embarked
340       2         1  female   4.0      2      1  39.0000        S
631       3         0    male  26.0      0      0   7.7750        S
660       3         1  female  24.0      0      3  19.2583        C
789       3         0    male   NaN      0      0   7.2250        C
679       3         0  female   9.0      1      1  15.2458        C

In [102]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['survived']),df['survived'],test_size=0.2,random_state=42)

In [103]:
x_train.head()

     pclass     sex   age  sibsp  parch      fare embarked
772       3    male  17.0      0      0    7.8958        S
543       2    male  36.0      0      0   10.5000        S
289       1  female  18.0      0      2   79.6500        S
10        1    male  47.0      1      0  227.5250        C
147       1    male   NaN      0      0   42.4000        S

In [104]:
y_train

772     0
543     0
289     1
10      0
147     0
       ..
1095    0
1130    0
1294    0
860     1
1126    0
Name: survived, Length: 1047, dtype: int64

In [105]:
from sklearn.impute import SimpleImputer
si_age = SimpleImputer()
si_fare = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

In [106]:
x_train_age = si_age.fit_transform(x_train[['age']])
x_test_age = si_age.transform(x_test[['age']])

x_train_fare = si_fare.fit_transform(x_train[['fare']])
x_test_fare = si_fare.transform(x_test[['fare']])

x_train_embarked = si_embarked.fit_transform(x_train[['embarked']])
x_test_embarked = si_embarked.transform(x_test[['embarked']])

In [107]:
x_train_age

array([[17. ],
       [36. ],
       [18. ],
       ...,
       [28.5],
       [26. ],
       [28. ]])

In [108]:
from sklearn.preprocessing import OneHotEncoder
ohe_sex = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

x_train_sex = ohe_sex.fit_transform(x_train[['sex']])
x_train_embarked = ohe_embarked.fit_transform(x_train_embarked)

x_test_sex = ohe_sex.transform(x_test[['sex']])
x_test_embarked = ohe_embarked.transform(x_test_embarked)

In [109]:
x_train_sex

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [110]:

X_train_rem = x_train.drop(columns=['sex','age','embarked'])
X_test_rem = x_test.drop(columns=['sex','age','embarked'])

In [111]:
X_train_transformed = np.concatenate((X_train_rem,x_train_age,x_train_sex,x_train_embarked),axis=1)
X_test_transformed = np.concatenate((X_test_rem,x_test_age,x_test_sex,x_test_embarked),axis=1)

In [118]:
X_train_transformed

array([[3., 0., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [1., 0., 2., ..., 0., 0., 1.],
       ...,
       [3., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.]])

In [115]:
from sklearn.tree import DecisionTreeClassifier

In [116]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [117]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1])

In [119]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7748091603053435

In [120]:
import pickle

In [122]:
import pickle
import os

os.makedirs('models', exist_ok=True)

with open('models/ohe_sex.pkl', 'wb') as f:
    pickle.dump(ohe_sex, f)

with open('models/ohe_embarked.pkl', 'wb') as f:
    pickle.dump(ohe_embarked, f)

with open('models/clf.pkl', 'wb') as f:
    pickle.dump(clf, f)

In [124]:

print(os.path.abspath('models'))

/kaggle/working/models