In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/faizanhaider01/cars-0/cars.csv

In [2]:
df = pd.read_csv("/kaggle/input/datasets/faizanhaider01/cars-0/cars.csv",usecols = ['age','miles','sales'])

In [3]:
df.sample(6)

     age  miles  sales
200   49     25  14328
199   50     31  19243
672   48     72  29138
79    36     22  15905
249   47     92  28553
336   53     33   7344

In [4]:
df.loc[df['sales'] < 15000, 'sales'] = 0
df.loc[df['sales'] >= 15000, 'sales'] = 1

In [5]:
df

     age  miles  sales
0     28     23      0
1     26     27      0
2     30     58      1
3     26     25      1
4     20     17      0
..   ...    ...    ...
958   22     11      0
959   19     23      0
960   28     28      0
961   50     29      1
962   47     15      0

[963 rows x 3 columns]

In [6]:
df['miles'].max()

97

In [7]:
from sklearn.preprocessing import Binarizer

from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [8]:
X = df.drop(columns=['sales'])
y = df['sales']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:

# Without binarization

clf = DecisionTreeClassifier()

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_test,y_pred)

0.7616580310880829

In [11]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.7652491408934707)

In [17]:

trf = ColumnTransformer([
    ('bin',Binarizer(threshold = 35 ,copy=False),[0])
],remainder='passthrough')

In [18]:

X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [20]:
pd.DataFrame(X_train_trf,columns=['age','miles']).sample(4)

     age  miles
105    0     23
282    1     34
112    1     20
196    0     40

In [21]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2 = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred2)

0.7823834196891192

In [22]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

np.float64(0.7974012027491408)